// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdYG0StQEhQ2BVrsQ5lUtUoZH1vPbpI4',
    appId: '1:181033990264:web:ccce093e99ec9e1cf3558d',
    messagingSenderId: '181033990264',
    projectId: 'aguada-32232',
    authDomain: 'aguada-32232.firebaseapp.com',
    storageBucket: 'aguada-32232.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9nk4-4ZLgCiyHCsd3ZfsfUbESHnYgZto',
    appId: '1:181033990264:android:774dbd56a7f2e4def3558d',
    messagingSenderId: '181033990264',
    projectId: 'aguada-32232',
    storageBucket: 'aguada-32232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZYQiI4y5F7MaEDPdCdhqeydKOO85oSfM',
    appId: '1:181033990264:ios:b61cfc9ee11e9cf6f3558d',
    messagingSenderId: '181033990264',
    projectId: 'aguada-32232',
    storageBucket: 'aguada-32232.appspot.com',
    iosClientId: '181033990264-g6l1ed09n33grglkv5v1ia7f5kidfpgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aguadaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZYQiI4y5F7MaEDPdCdhqeydKOO85oSfM',
    appId: '1:181033990264:ios:b61cfc9ee11e9cf6f3558d',
    messagingSenderId: '181033990264',
    projectId: 'aguada-32232',
    storageBucket: 'aguada-32232.appspot.com',
    iosClientId: '181033990264-g6l1ed09n33grglkv5v1ia7f5kidfpgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aguadaa',
  );
}
